name: FFQ
on:
  push:
    branches:
      - 'master'
    tags-ignore:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  build:
    if: "contains(github.event.head_commit.message, '[deploy prod]')"
    name: Build FFQ
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Environment
        run: env | sort

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.TOWER_CI_AWS_ACCESS }}
          aws-secret-access-key: ${{ secrets.TOWER_CI_AWS_SECRET }}
          aws-region: eu-west-2

      - name: Deploy to prod
        uses: kodermax/kubectl-aws-eks@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA_LONDON }}
        with:
          args: set image deployment/ffq-app ffq-app=public.ecr.aws/seqera-labs/ffq:$(cat VERSION) -n ffq-prod
